global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Configuration des r√®gles d'alertes
rule_files:
  - "/etc/prometheus/prometheus_alerts.yml"

scrape_configs:
  - job_name: "postgres"
    static_configs:
      - targets: ["pg_exporter:9187"]
